# app/core/intent_examples.py

INTENT_EXAMPLES = {
    "formalizacion_negocio": [
        "Quiero saber qué necesito para formalizar mi negocio",
        "Cómo saco mi RUC para empezar mi negocio",
        "Qué pasos debo seguir para formalizar una empresa pequeña",
        "Qué debo hacer para registrar mi negocio ante SUNAT",
        "Cómo inicio un negocio formal en Perú",
        "Qué necesito para sacar RUC",
        "Cómo puedo formalizar mi MYPE",
        "Quiero formalizar mi microempresa con trabajadores",
        "Cómo registro una pequeña empresa con empleados",
        "Qué necesito para formalizar un negocio con varios trabajadores",
        "Quiero crear mi empresa formalmente y contratar personal",
        "Cómo formalizo un negocio que ya tengo funcionando",
        "Pasos para iniciar formalmente una MYPE en Perú",
        "Quiero inscribir mi negocio en SUNAT",
        "Cómo legalizar mi negocio pequeño",
        "Cuáles son los beneficios de formalizar mi negocio",
        "Qué ventajas tiene registrarme en SUNAT",
        "Por qué me conviene formalizar mi empresa",
        "Qué gano si formalizo mi negocio en Perú",
        "Beneficios tributarios de tener un negocio formal",
        # Consultas cortas y directas sobre RUC
        "cómo saco mi RUC",
        "sacar RUC",
        "quiero sacar mi RUC",
        "cómo me registro en SUNAT",
        "qué es el RUC",
        "para qué sirve el RUC",
        "dónde saco el RUC",
        "quiero inscribirme en SUNAT",
        "cómo obtener RUC",
        "obtener mi RUC",
    ],
    "multas_y_sanciones": [
        "Me llegó una multa por declarar fuera de fecha",
        "Qué pasa si no presenté mi declaración a tiempo",
        "Quiero saber cuánto me pueden cobrar de multa por no declarar",
        "Hay sanción si no cumplo con mis obligaciones tributarias",
        "Qué multa hay por declarar tarde",
        "Tengo una sanción tributaria y quiero entenderla",
        "Cómo puedo reducir una multa de SUNAT",
        "Me notificaron una infracción tributaria",
        "Cuánto es la multa por no emitir comprobante",
        "Puedo apelar una sanción de SUNAT",
        "Cómo se calcula la UIT para las multas",
        "Cuáles son las infracciones vinculadas a las declaraciones juradas",
        "Qué infracciones existen por no presentar la declaración jurada",
        "Cuáles son las sanciones por omitir la declaración de impuestos",
        "Infracciones tributarias relacionadas con declarar incorrectamente",
        "Qué pasa si declaro cifras falsas en mi declaración jurada",
        "Hay multa si no presento la declaración anual de renta",
        "Cuáles son las infracciones más comunes en declaraciones tributarias",
        # Consultas cortas sobre multas
        "tengo una multa",
        "me multaron",
        "infracción tributaria",
        "sanción SUNAT",
        "cómo pago mi multa",
        "reducir multa",
        "gradualidad de multas",
    ],
    "regimenes_tributarios": [
        "Qué régimen tributario me conviene para una bodega pequeña",
        "Cuál es la diferencia entre NRUS y RER",
        "Cómo saber en qué régimen tributario debería estar mi negocio",
        "Qué régimen me conviene si recién empiezo a vender",
        "Cuál es el mejor régimen para un pequeño negocio",
        "Qué régimen tributario debo elegir",
        "Cuáles son los regímenes tributarios disponibles en Perú",
        "Diferencia entre Nuevo RUS y Régimen MYPE Tributario",
        "Qué impuesto pago en el RER",
        "Cuánto se paga en el Régimen MYPE Tributario",
        "Quiero comparar los regímenes para ver cuál me sale más barato",
        # Siglas y nombres cortos
        "qué es el RMT",
        "qué es RMT",
        "qué es el RUS",
        "qué es el Nuevo RUS",
        "qué es el RER",
        "qué es el NRUS",
        "RMT",
        "RER",
        "RUS",
        "NRUS",
        "régimen MYPE",
        "cuánto pago en el RMT",
        "cuánto pago en el RUS",
        "límite del RUS",
        "límite del RER",
        "tasa del RMT",
        "diferencia RUS y RMT",
        "diferencia RER y RMT",
        "qué es el régimen especial de renta",
        "qué es el régimen MYPE tributario",
        "en qué régimen estoy",
        "cambiar de régimen tributario",
    ],
    "comprobantes_pago": [
        "Cómo emito una boleta o factura",
        "Qué comprobante de pago debo entregar a mi cliente",
        "Cuándo corresponde emitir factura y cuándo boleta",
        "Quiero saber cómo generar comprobantes de pago",
        "Cómo se emiten comprobantes en SUNAT",
        "Qué diferencia hay entre boleta y factura",
        "Cómo emito factura electrónica",
        "Qué es una nota de crédito y cómo se usa",
        "Puedo anular una boleta ya emitida",
        "Mis clientes me piden factura, cómo la genero",
        "Qué es el SEE de SUNAT para facturación electrónica",
        # Consultas cortas
        "cómo emito una boleta",
        "cómo emito una factura",
        "comprobante electrónico",
        "factura electrónica",
        "boleta electrónica",
        "qué es una boleta",
        "qué es una factura",
        "diferencia boleta factura",
        "nota de crédito",
        "anular comprobante",
    ],
    "cronograma_obligaciones": [
        "Cuándo vence mi declaración mensual",
        "Cuál es la fecha límite para declarar impuestos este mes",
        "Dónde consulto el cronograma de vencimientos de SUNAT",
        "Qué día me toca presentar mis obligaciones tributarias",
        "Cuándo tengo que declarar este mes",
        "Cómo reviso mi fecha de vencimiento",
        "Cuándo tengo que pagar mis impuestos",
        "Cuál es el plazo para presentar el PDT",
        "En qué fecha vence el IGV de este mes",
        "Cuándo es la próxima fecha de declaración",
        "Qué pasa si declaro después de la fecha de vencimiento",
        # Consultas cortas
        "fecha de vencimiento",
        "cuándo declaro",
        "cronograma tributario",
        "vencimiento IGV",
        "fecha límite declaración",
        "calendario SUNAT",
        "cuándo pago IGV",
    ],
    "declaraciones_impuestos": [
        "Cómo hago la declaración mensual de IGV y Renta",
        "Cómo presento mi declaración mensual en SUNAT",
        "Qué es el PDT 621 y cómo se llena",
        "Cómo declaro el IGV mensualmente",
        "Pasos para hacer la declaración mensual",
        "Cómo usar el formulario 621 de SUNAT",
        "Qué datos necesito para declarar el IGV",
        "Cómo hago mi declaración jurada anual",
        "Qué es la declaración anual de renta",
        "Tengo que presentar declaración mensual, cómo lo hago",
        "Cómo accedo al PDT para declarar",
        "Declaración de impuestos para pequeños negocios",
        "Cómo pago el IGV mensual",
        "Qué es el IGV y cómo se declara",
        # Consultas cortas
        "declaración mensual",
        "declarar IGV",
        "PDT 621",
        "formulario 621",
        "declaración jurada",
        "cómo declaro",
        "IGV mensual",
        "declaración anual",
        "cómo pago impuestos",
    ],
}
